# This template uses jdk8 for verifying and deploying images
image: maven:latest

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/repository/

build:
  stage: build
  script:
    - mvn compile package
  artifacts:
    name: "ConfigurationLibrary.jar"
    paths:
      - target/ConfigurationLibrary-*.jar

# For merge requests do not `deploy` but only run `verify`.
# See https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html
.verify: &verify
  stage: test
  script:
    - 'mvn verify'

# Verify merge requests using JDK8
verify:
  <<: *verify
